name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Vérifier la présence de index.html
        id: check_index
        uses: andstor/file-existence-action@v1
        with:
          files: "./src/frontend/index.html"

      - name: indexExist
        if: steps.check_index.outputs.files_exists == 'true'
        run: echo "✅ Le fichier index.html existe."

      - name: indexNotExist
        if: steps.check_index.outputs.files_exists != 'true'
        run: |
          echo "❌ Erreur : index.html n’existe pas!"
          exit 1
            
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_SMOKE_014BEFE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src/frontend"
          api_location: ""
          output_location: "."

      - name: Exécuter Lighthouse sur le build
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://module-210.romainkolly.emf-informatique.ch
          #budgetPath: .github\lighthouse-budget.json
          configPath: .github/lighthouserc.json
          uploadArtifacts: false
          temporaryPublicStorage: true

      - name: Vérification des scores Lighthouse
        if: failure()
        run: |
          echo "❌ Score Lighthouse trop faible! Vérifiez le rapport et améliorez les performances."
          exit 1

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_SMOKE_014BEFE03 }}
          action: "close"
